//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyShrikeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public System.Guid Id { get; set; }
        public System.Guid CreatedBy { get; set; }
        public string SingleLineInput { get; set; }
        public string Paragraph { get; set; }
        public bool RadioButton { get; set; }
        public int Dropdown { get; set; }
        public bool IsPublish { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
